//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCarMotorbike.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string AdminID { get; set; }
        public string AdminPassword { get; set; }
        public byte[] AdminEmail { get; set; }
        public string AdminName { get; set; }
    }
}
