//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCarMotorbike.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Employee
    {
        [DisplayName("Employee ID")]
        public string EmployeeID { get; set; }
        [DisplayName("Employee Name")]
        public string EmployeeName { get; set; }
        [DisplayName("Employee Email")]
        public string EmployeeEmail { get; set; }
        [DisplayName("Employee Phone")]
        public string EmployeePhone { get; set; }
        [DisplayName("Employee Password")]
        public string EmployeePassword { get; set; }
    }
}
