//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCarMotorbike.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Rent
    {
        [DisplayName("Rent Code")]
        public string RentID { get; set; }
        public string CustomerID { get; set; }
        [DisplayName("Rent Create")]
        public string RentCreatAt { get; set; }
        [DisplayName("Rent Status")]
        public string RentStatus { get; set; }
        [DisplayName("Rent Start")]
        public string RentPickUpDate { get; set; }
        [DisplayName("Rent End")]
        public string RentReturnDate { get; set; }
        [DisplayName("Rent Cost")]
        public Nullable<int> RentTotalPrice { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeePhone { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RentDetail RentDetail { get; set; }
    }
}
