//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCarMotorbike.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentDetail
    {
        public string RentID { get; set; }
        public string VehicleID { get; set; }
        public string CustomerID { get; set; }
    
        public virtual Rent Rent { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
